Ability to attach watermark when upload images to gallery
optimistdigital/nova-media-field pull request #41
Opened 2021-09-13 09:13 UTC by pitchayakit

2021-10-01 15:27 UTC, Tarpsvo requested changes
Hi @pitchayakit! Thanks a lot for the suggestion and PR. :)

I looked over your code and brought up some questions. The main issue is that your flow currently saves and compresses the image twice. If you could address that, we'd be happy to merge the PR.

2021-10-01 15:27 UTC, Tarpsvo commented on src/Classes/MediaHandler.php
> +                $watermark = Image::make($image_watermart_path);
Shouldn't this be after the original file is saved in the original flow at line 342? See: https://github.com/optimistdigital/nova-media-field/blob/dbc381af185600f545f5cc487e72e61456762b0c/src/Classes/MediaHandler.php#L340-L344

Your code seems to compress and save the images twice.

2021-10-01 15:27 UTC, Tarpsvo commented on src/Classes/MediaHandler.php
> +            if(!is_null($image_watermart_path)) {
This check should move to line 342 as well.

2021-10-04 11:21 UTC, pitchayakit commented
I'm looking forward to your feedback. 
For the last step, I'm happy to update readme as well  :)

2021-10-29 13:12 UTC, merged

2021-10-29 14:49 UTC, Tarpsvo commented
Thanks for the PR! I released it in version 2.1.0. :)